<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>JS Promises</title>
	<script>
		/*
			Promises
			- Handle asynchronous code
			- Can be used to avoid callback hell scenario (Using promise chaining)
			- Two properties - state and result (result only in case of resolve/rejected)
			Promises States -
			1. Pending
			2. Resolved (Fulfilled)
			3. Rejected
			2 Ways:
			Pending -> Resolved -> Setelled
			Pending -> Rejected -> Setelled
			// Define a promise
			let promise = new Promise ((resolve, reject) => {
				// 'resolve' method is for fulfilling the promise (Can send a resolvedMessage - optional)
				// 'reject' method is for rejecting the promise (Can send a rejectedMessage - optional)
			})
			// Handle a promise
			.then method callback -> For executing in case the promise was resolved 
			(Can have a parameter for resolvedMessage - optional)
			.catch method callback -> For executing in case the promise was rejected 
			(Can have a parameter for rejectedMessage - optional)
		*/

		// let promise = new Promise((resolve, reject) => {
		// 	resolve('Hey, I was resolved!')
		// })

		// promise.then((resolvedMessage) => {
		// 	console.log('Promise was resolved with the message: ' + resolvedMessage)
		// }).catch((rejectedMessage) => {
		// 	console.log('Promise was rejected with the message: ' + rejectedMessage)
		// })

		// Handling rejection is also possible using second callback of .then method
		// promise.then((resolvedMessage) => {
		// 	console.log('Promise was resolved with the message: ' + resolvedMessage)
		// }, (rejectedMessage) => {
		// 	console.log('Promise was rejected with the message: ' + rejectedMessage)
		// })

		// const promise1 = () => {
		// 	return new Promise((resolve, reject) => {
		// 		reject('Hey, I was rejected!')
		// 	})
		// }

		// promise1().then((resolvedMessage) => {
		// 	console.log('Promise was resolved with the message: ' + resolvedMessage)
		// }).catch((rejectedMessage) => {
		// 	console.log('Promise was rejected with the message: ' + rejectedMessage)
		// })

		// Promise chaining: (when you return a value from .then() method - returned value again becomes a promise which needs to be handled by .then() chaining)
		// 1. When first .then handler returns another promise which needs to be handled by chaining another .then()
		// 2. Return any data from first .then() and that data can be caught by the second .then() handler which is chained to the first one

		// const promise1 = () => {
		// 	return new Promise((resolve, reject) => {
		// 		setTimeout(() => {
		// 			resolve('A + ')
		// 		}, 2000)
		// 	})
		// } 

		// promise1().then((resolvedMessage) => {
		// 	return resolvedMessage + 'B + '
		// }).then((resolvedMessage) => {
		// 	return resolvedMessage + 'C'
		// }).then((resolvedMessage) => {
		// 	console.log(resolvedMessage)
		// }).catch((rejectedMessage) => {
		// 	console.log('Promise was rejected with the message: ' + rejectedMessage)
		// })


        /*
			Order placed 
			After 2s -> Chef received the order and started preparing
			After 10s -> Pizza Sauce added
			After 5s -> First layer of cheeze added
			After 12s -> Toppings added
			After 5s -> Second layer of cheeze added
			After 15s -> Pizza baked!
			After 8s -> Oregano added and packed
			After 2s -> Package received at counter
			The order is ready and handed over to the Zomato delivery guy!
		*/

		const chefReceived = () => {
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					console.log('Chef received the order and started preparing')
					resolve()
				}, 2000)
			})
		}

		const pizzaSauceAdded = () => {
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					console.log('Pizza Sauce added')
					resolve()
				}, 10000)
			})
		}

		const firstLayerOfCheezeAdded = () => {
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					console.log('First layer of cheeze added')
					resolve()
				}, 5000)
			})
		}

		const toppingsAdded = () => {
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					console.log('Toppings added')
					resolve()
				}, 12000)
			})
		}

		const secondLayerOfCheezeAdded = () => {
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					console.log('Second layer of cheeze added')
					resolve()
				}, 5000)
			})
		}

		const pizzaBaked = () => {
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					console.log('Pizza baked!')
					resolve()
				}, 15000)
			})
		}

		const oreganoAddedAndPacked = () => {
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					console.log('Oregano added and packed')
					resolve()
				}, 8000)
			})
		}

		const packageReceivedAtCounter = () => {
			return new Promise((resolve, reject) => {
				setTimeout(() => {
					console.log('Package received at counter')
					resolve()
				}, 2000)
			})
		}

		const executeOrder = () => {
			console.log('Order placed')
			chefReceived()
				.then(pizzaSauceAdded)
				.then(firstLayerOfCheezeAdded)
				.then(toppingsAdded)
				.then(secondLayerOfCheezeAdded)
				.then(pizzaBaked)
				.then(oreganoAddedAndPacked)
				.then(packageReceivedAtCounter)
				.then(() => console.log('The order is ready and handed over to the Zomato delivery guy!'))
				.catch((err) => console.log(err))
		}
	</script>
</head>
<body>
	<button
	onclick="executeOrder()">Execute Order
</button>
</body>
</html> 